import type { Metadata } from "next";
import '..//globals.css';
import { GooglePhotosService } from "@/service/service";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Initialize the storage once at the layout level
  const photosService = new GooglePhotosService();
  await photosService.initializeStorage();

  return (
    <html lang="en">
      <body
        className={`bg-red-50`}
      >
        {children}
      </body>
    </html>
  );
}
